import { Toaster } from "@/components/ui/sonner";
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full h-screen flex justify-center items-center">
        <main>
          {children}
          <Toaster position="top-right" richColors/>
        </main>
      </body>
    </html>
  )
}
